### ISSUE TITLE
[Idea] Getting this extension to work on Windows

### ISSUE THREAD

**Issue by CasualDev242** [light-and-ray/sd-webui-face-manipulation-extras#3]
I took the lazy route and asked Perplexity AI if this project could be made compatible with Windows. As it's an AI it's prone to false info, but here is what it said:

 

> To address the compatibility issue with Windows for the sd-webui-face-manipulation-extras extension, we need to consider a few points:
> 
> 1. The aimrocks package incompatibility:
> The aimrocks package, which is a dependency for the aim package, is indeed not compatible with Windows. However, this doesn't necessarily mean that the entire extension cannot work on Windows.
> 
> 2. Stylegan2-pytorch compatibility:
> You are correct in questioning the statement about stylegan2-pytorch requiring the aim package. Stylegan2-pytorch is generally Windows-compatible, and the aim package is not a direct dependency for it.
> 
> To make this extension work on Windows, we could consider the following alternatives:
> 
> ## Alternative Approaches
> 
> 1. **Remove aim dependency:**
> If the aim package is not crucial for the core functionality of the extension, it could be removed from the dependencies. This would eliminate the need for aimrocks and potentially resolve the Windows compatibility issue.
> 
> 2. **Use a different logging library:**
> If experiment tracking is necessary, alternatives to aim could be used that are Windows-compatible. Some options include:
> 
>    - **MLflow**: A popular open-source platform for managing the machine learning lifecycle.
>    - **Weights & Biases (wandb)**: A tool for experiment tracking and visualization.
>    - **TensorBoard**: While primarily associated with TensorFlow, it can be used with PyTorch as well.
> 
> 3. **Use a Windows-compatible database:**
> If local data storage is needed, alternatives to RocksDB (which aimrocks wraps) could be considered:
> 
>    - **SQLite**: A lightweight, file-based database that works well on Windows.
>    - **LevelDB**: Another key-value store that has Windows support.
> 
> 4. **Containerization:**
> Using Docker to containerize the application could potentially bypass Windows-specific issues, allowing the use of Linux-compatible packages within the container.
> 
> ## Implementation Steps
> 
> To implement these changes, the extension's maintainer would need to:
> 
> 1. Review the codebase to determine if aim is actually necessary for the extension's functionality.
> 
> 2. If aim is not crucial, remove it from the dependencies and adjust any code that uses it.
> 
> 3. If experiment tracking is needed, implement one of the suggested alternatives (e.g., MLflow or wandb) and update the code accordingly.
> 
> 4. Update the `requirements.txt` file to reflect the new dependencies.
> 
> 5. Test the modified extension thoroughly on both Windows and Linux systems.
> 
> By taking these steps, it's likely that the extension could be made compatible with Windows without sacrificing functionality[1]. However, it's important to note that this would require significant effort from the extension's maintainer and potentially a redesign of certain aspects of the code.
> 
> Citations:
> [1] https://github.com/light-and-ray/sd-webui-face-manipulation-extras
> [2] https://pub.aimind.so/generating-images-with-stylegan2-ada-model-on-google-colab-pro-platform-using-pytorch-framework-da8ee5adee70?gi=b81c1930bee2
> [3] https://github.com/NVlabs/stylegan2
> [4] https://github.com/lucidrains/stylegan2-pytorch
> [5] https://blog.paperspace.com/how-to-set-up-stylegan2-ada-pytorch-on-paperspace/
> [6] https://github.com/NVlabs/stylegan2-ada-pytorch
> 

Assuming this information is correct, can you help explain to me more of how your code works? If this is a feasible project I might take a crack at implementing a Windows version.

**Comment by light-and-ray** [comment]
Yes, aimrocks is incompatible with Windows. But my extension doesn't depend on it directly. You can see it in [install.py](https://github.com/light-and-ray/sd-webui-face-manipulation-extras/blob/master/install.py) file. It depends directly only on dlib-bin and ninja. This dependence is indirect, I guess it's already installed in linux's ninja

This answer is not very useful, because there are [avivga/zerodim](https://github.com/avivga/zerodim) and [stylegan2-pytorch](https://github.com/rosinality/stylegan2-pytorch) projects which are copied into this extension.

I guess this dependencies are needed to compile cuda code on fly. For Windows it's needed to precompile this code, but I don't know how. It's the only opensource face manipulation project I've found 🤷🏻‍♀️
